# Generated by Django 4.0.2 on 2022-03-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.CharField(blank=True, choices=[('太极', 'taiji'), ('瑜伽', 'yoga')], max_length=20, null=True, verbose_name='your hobbies'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idcard_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='ID card'),
        ),
    ]
